=== jmiszczak/mypubs/publications.dtd
<!ELEMENT article ( arxiv | authors | book-title | doi | editors | journal | number | pages | pdf-file | times-cited | title | volume | year )* >
<!ATTLIST article key ID #REQUIRED >

<!ELEMENT arxiv ( #PCDATA ) >

<!ELEMENT author ( #PCDATA ) >

<!ELEMENT authors ( author+ ) >

<!ELEMENT book ( authors, title, publisher, year, month?, doi?, volume?, series?, isbn?, edition? ) >
<!ATTLIST book key NMTOKEN #REQUIRED >

<!ELEMENT book-title ( #PCDATA ) >

<!ELEMENT doi ( #PCDATA ) >

<!ELEMENT edition ( #PCDATA ) >

<!ELEMENT editor ( #PCDATA ) >

<!ELEMENT editors ( editor+ ) >

<!ELEMENT isbn EMPTY >

<!ELEMENT journal ( #PCDATA ) >

<!ELEMENT month ( #PCDATA ) >

<!ELEMENT number ( #PCDATA ) >

<!ELEMENT pages ( #PCDATA ) >

<!ELEMENT pdf-file ( #PCDATA ) >

<!ELEMENT preprint ( arxiv | authors | title | year )* >
<!ATTLIST preprint key NMTOKEN #REQUIRED >

<!ELEMENT publications ( article+, book+, preprint+ ) >

<!ELEMENT publisher ( #PCDATA ) >

<!ELEMENT series ( #PCDATA ) >

<!ELEMENT times-cited ( #PCDATA ) >
<!ATTLIST times-cited source ( gs | jcr ) #REQUIRED >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT volume ( #PCDATA ) >

<!ELEMENT year ( #PCDATA ) >

=== jmiszczak/mypubs/publications.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE publications SYSTEM 'publications.dtd'>

<publications>

<!-- papers -->

<article key="glos18qswalk">
  <authors>
    <author>A. Glos</author>
    <author>J.A. Miszczak</author>
    <author>M. Ostaszewski</author>
  </authors>
  <title>QSWalk.jl: Julia package for quantum stochastic walks analysis</title>
  <journal>Comput. Phys. Commun.</journal>
  <doi>10.1016/j.cpc.2018.09.001</doi>
  <volume>in press</volume>
  <arxiv>1801.01294</arxiv>
  <year>2018</year>
</article>

<article key="glos18limiting">
  <authors>
    <author>A. Glos</author>
    <author>J.A. Miszczak</author>
    <author>M. Ostaszewski</author>
  </authors>
  <title>Limiting properties of stochastic quantum walks on directed graphs</title>
  <journal>J. Phys. A: Math. Theor.</journal>
  <volume>51</volume>
  <number>3</number>
  <pages>035304</pages>
  <arxiv>1703.01792</arxiv>
  <doi>10.1088/1751-8121/aa9a4a</doi>
  <year>2018</year>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/glos18limiting.pdf</pdf-file>
</article>

<article key="glos18role">
  <authors>
    <author>A. Glos</author>
    <author>J.A. Miszczak</author>
  </authors>
  <title>The role of quantum correlations in Cop and Robber game</title>
  <journal>Quantum Stud.: Math. Found.</journal>
  <arxiv>1702.07932</arxiv>
  <doi>10.1007/s40509-017-0148-4</doi>
  <year>2018</year>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/glos18role.pdf</pdf-file>
</article>

<article key="miszczak17states">
  <authors>
    <author>J.A. Miszczak</author>
  </authors>
  <title>States and channels in quantum mechanics without complex numbers</title>
  <journal>Springer Proceedings in Mathematics &amp; Statistics. Proc. of ACA 2015: Applications of Computer Algebra</journal>
  <volume>198</volume>
  <pages>305-316</pages>
  <arxiv>1603.04787</arxiv>
  <doi>10.1007/978-3-319-56932-1_21</doi>
  <year>2017</year>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/miszczak17states.pdf</pdf-file>
</article>

<article key="puchala17symbolic">
  <authors>
    <author>Z. Puchała</author>
    <author>J.A. Miszczak</author>
  </authors>
  <title>Symbolic integration with respect to the Haar measure on the unitary group</title>
  <journal>Bull. Pol. Acad. Sci.-Tech. Sci</journal>
  <volume>65</volume>
  <number>1</number>
  <pages>21-27</pages>
  <arxiv>1109.4244</arxiv>
  <doi>10.1515/bpasts-2017-0003</doi>
  <year>2017</year>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/puchala17symbolic.pdf</pdf-file>
</article>

<article key="sergioli17quantum-inspired">
  <authors>
    <author>G. Sergioli</author>
    <author>E. Santucci</author>
    <author>L. Didaci</author>
    <author>J.A. Miszczak</author>
    <author>R. Giuntini</author>
  </authors>
  <title>A quantum-inspired version of the nearest mean classifier</title>
  <journal>Soft Computing</journal>
  <volume>22</volume>
  <number>3</number>
  <pages>691-705</pages>
  <doi>10.1007/s00500-016-2478-2</doi>
  <arxiv>1603.00173</arxiv>
  <year>2017</year>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/sergioli17quantum-inspired.pdf</pdf-file>
</article>

<article key="sadowski16lively">
  <authors>
    <author>P. Sadowski</author>
    <author>J.A. Miszczak</author>
    <author>M. Ostaszewski</author>
  </authors>
  <title>Lively quantum walks on cycles</title>
  <journal>J. Phys. A: Math. Theor.</journal>
  <volume>49</volume>
  <number>37</number>
  <pages>375302</pages>
  <arxiv>1512.02802</arxiv>
  <doi>10.1088/1751-8113/49/37/375302</doi>
  <year>2016</year>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/sadowski16lively.pdf</pdf-file>
</article>

<article key="zawadzki16general">
  <authors>
    <author>P. Zawadzki</author>
    <author>J.A. Miszczak</author>
  </authors>
  <title>A general scheme for information interception in the ping pong protocol</title>
  <journal>Advances in Mathematical Physics</journal>
  <volume>2016</volume>
  <pages>3162012</pages>
  <arxiv>1606.02108</arxiv>
  <doi>10.1155/2016/3162012</doi>
  <year>2016</year>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/zawadzki16general.pdf</pdf-file>
</article>

<article key="pawela15generalized">
  <authors>
    <author>Ł. Pawela</author>
    <author>P. Gawron</author>
    <author>J.A. Miszczak</author>
    <author>P. Sadowski</author>
  </authors>
  <title>Generalized open quantum walks on Apollonian networks</title>
  <journal>PLoS ONE</journal>
  <volume>10</volume>
  <number>7</number>
  <pages>e0130967</pages>
  <year>2015</year>
  <arxiv>1407.1184</arxiv>
  <doi>10.1371/journal.pone.0130967</doi>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/pawela15generalized.pdf</pdf-file>
</article>

<article key="miszczak14exploration">
  <authors>
    <author>J.A. Miszczak</author>
    <author>P. Sadowski</author>
  </authors>
  <title>Quantum network exploration with a faulty sense of direction</title>
  <journal>Quantum Information &amp; Computation</journal>
  <volume>14</volume>
  <number>13&amp;14</number>
  <pages>1238-1250</pages>
  <year>2014</year> 
  <arxiv>1308.5923</arxiv>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/miszczak14exploration.pdf</pdf-file>
</article>

<article key="miszczak14general">
  <authors>
    <author>J.A. Miszczak</author>
    <author>Ł. Pawela</author>
    <author>J. Sładkowski</author>
  </authors>
  <title>General model for a entanglement-enhanced composed quantum game on a two-dimensional lattice</title>
  <journal>Fluctuation and Noise Letters</journal>
  <volume>13</volume>
  <number>2</number>
  <pages>1450012</pages>
  <year>2014</year>
  <arxiv>1306.4506</arxiv>
  <doi>10.1142/S0219477514500126</doi>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/miszczak14general.pdf</pdf-file>
</article>

<article key="mcgettrick14quantum">
  <authors>
    <author>M. Mc Gettrick</author>
    <author>J.A. Miszczak</author>
  </authors>
  <title>Quantum walks with memory on cycles</title>
  <journal>Physica A</journal>
  <volume>399</volume>
  <pages>163-170</pages>
  <arxiv>1301.2905</arxiv>
  <year>2014</year>
  <doi>10.1016/j.physa.2014.01.002</doi>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/mcgettrick14quantum.pdf</pdf-file>
</article>


<article key="miszczak13functional">
  <authors>
    <author>J.A. Miszczak</author>
  </authors>
  <title>Functional framework for representing and transforming quantum channels</title>
  <book-title>Proc. Applications of Computer Algebra (ACA2013), Malaga, 2-6 July 2013</book-title>
  <editors>
    <editor>J.L. Galan Garcia</editor>
    <editor>G. Aguilera Venegas</editor>
    <editor>P. Rodriguez Cielos</editor>
  </editors>
  <pages>276-280</pages>
  <year>2013</year>
  <arxiv>1307.4906</arxiv>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/miszczak13functional.pdf</pdf-file>
</article>

<article key="winiarczyk13analysis">
  <authors>
    <author>R. Winiarczyk</author>
    <author>P. Gawron</author>
    <author>J.A. Miszczak</author>
    <author>Ł. Pawela</author>
    <author>Z. Puchała</author>
  </authors>
  <title>Analysis of patent activity in the field of quantum information processing</title>
  <journal>Int. J. Quantum Inform.</journal> 
  <volume>11</volume> 
  <number>01</number>
  <pages>1350007</pages> 
  <year>2013</year>
  <arxiv>1212.2439</arxiv>
  <doi>10.1142/S021974991350007X</doi>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/winiarczyk13analysis.pdf</pdf-file>
</article>

<article key="miszczak13employing">
  <authors>
    <author>J.A. Miszczak</author>
  </authors>
  <title>Employing online quantum random number generators for generating truly random quantum states in Mathematica</title>
  <journal>Comput. Phys. Commun.</journal>	
  <year>2013</year>
  <volume>184</volume>
  <number>1</number>
  <pages>257–258</pages>
  <doi>10.1016/j.cpc.2012.08.012</doi>
  <arxiv>1208.3970</arxiv>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/miszczak13employing.pdf</pdf-file>
</article>

<article key="zawadzki13increasing">
  <authors>
    <author>P. Zawadzki</author>
    <author>Z. Puchała</author>
    <author>J.A. Miszczak</author>
  </authors>
  <title>Increasing the security of the ping-pong protocol by using many mutually unbiased bases</title>
  <journal>Quantum Inf. Process.</journal>
  <year>2013</year>
  <volume>12</volume>
  <number>1</number>
  <pages>569-576</pages>
  <doi>10.1007/s11128-012-0403-x</doi>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/zawadzki13increasing.pdf</pdf-file>
  <arxiv>1201.3230</arxiv>
  <times-cited source="jcr"></times-cited>
  <times-cited source="gs"></times-cited>
</article>

<article key="puchala12restricted">
  <authors>
    <author>Z. Puchała</author>
    <author>J.A. Miszczak</author>
    <author>P. Gawron</author>
    <author>C.F. Dunkl</author>
    <author>J.A. Holbrook</author>
    <author>K. Życzkowski</author>
  </authors>
  <title>Restricted numerical shadow and geometry of quantum entanglement</title>
  <journal>J. Phys. A-Math. Theor.</journal>
  <year>2012</year>
  <volume>45</volume>
  <number>41</number>
  <doi>10.1088/1751-8113/45/41/415309</doi>
  <pages>415309</pages>
  <arxiv>1201.2524</arxiv>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/puchala12restricted.pdf</pdf-file>
  <times-cited source="jcr">1</times-cited>
  <times-cited source="gs"></times-cited>
</article>

<article key="miszczak12qubit">
  <authors>
    <author>J.A. Miszczak</author>
    <author>P. Gawron</author>
    <author>Z. Puchała</author>
  </authors>
  <title>Qubit flip game on a Heisenberg spin chain</title>
  <journal>Quantum Inf. Process.</journal>
  <year>2012</year>
  <volume>11</volume>
  <number>6</number>
  <pages>1571-1583</pages>
  <arxiv>1108.0642</arxiv>
  <doi>10.1007/s11128-011-0322-2</doi>
  <pdf-file>https://iitis.pl/~miszczak/files/papers/miszczak12qubit.pdf</pdf-file>
  <times-cited source="jcr"></times-cited>
  <times-cited source="gs">1</times-cited>
</article>

<article key="puchala11probability">
  <authors>
